KINGDOMS = [
  { name: 'The North', description: 'A maior região de Westeros, conhecida pelos invernos frios e vasta wilderness, governada pela família Stark. O Norte é caracterizado por suas vastas florestas, montanhas e grandes lagos, e é o lar de algumas das maiores casas de Westeros, que lutam para manter a ordem em uma terra vasta e implacável.' },
  { name: 'The Reach', description: 'Uma região fértil e populosa conhecida pela agricultura, vinho e pela sede da Casa Tyrell. O Reach é famoso por suas vinhas exuberantes, suas flores vibrantes e seus campos férteis. A casa Tyrell tem uma forte influência política e econômica na região, e é uma das casas mais ricas de Westeros.' },
  { name: 'The Vale', description: 'Uma região montanhosa conhecida por suas fortalezas impenetráveis e isolamento, governada pela Casa Arryn. O Vale é conhecido por sua paisagem acidentada e fortificações naturais. A Casa Arryn é uma das casas mais antigas de Westeros, e seu domínio é marcado pela segurança e pela tradição.' },
  { name: 'The Stormlands', description: 'Uma região áspera propensa a tempestades e ataques costeiros, governada pela Casa Baratheon. As Terras das Tempestades são conhecidas por seu clima severo e pela bravura de seus habitantes. A Casa Baratheon, conhecida por sua força militar, defende a região contra invasores e tempestades.' },
  { name: 'Dorne', description: 'Uma região quente e árida no sul, conhecida por seu povo apaixonado e independência feroz, governada pela Casa Martell. Dorne é famosa por seu clima escaldante e por seus habitantes destemidos. A Casa Martell é conhecida por sua resistência e por suas estratégias militares únicas.' },
  { name: 'The Riverlands', description: 'Uma região central com numerosos rios e terras férteis, governada pela Casa Tully. Os Rios são conhecidos por suas terras férteis e pela importância estratégica dos rios que cortam a região. A Casa Tully é conhecida por sua habilidade em gerir e proteger essa região vital.' },
  { name: 'The Iron Islands', description: 'Um grupo de ilhas severas e tempestuosas, conhecido por seus invasores marítimos, governado pela Casa Greyjoy. As Ilhas de Ferro são famosas por suas tempestades constantes e pelo caráter resistente de seus habitantes. A Casa Greyjoy domina as ilhas com uma força naval temida em Westeros.' },
  { name: 'Westerlands', description: 'Uma região rica e montanhosa, governada pela Casa Lannister. Os Westerlands são conhecidos por suas vastas minas de ouro e sua riqueza, além de sua influência política significativa. A Casa Lannister é uma das casas mais poderosas e ricas de Westeros, com uma longa história de riqueza e poder.' }

]

LOCATIONS = [
  { kingdom_name: 'The North', name: 'Winterfell', description: 'A sede ancestral da Casa Stark, localizada no coração do Norte. Winterfell é uma imponente fortaleza com grandes muralhas e criptas antigas. O castelo serve como centro de governo e residência para a família Stark, cercado por vastas florestas e lagos. É um símbolo de resistência e tradição para o Norte.' },
  { kingdom_name: 'The North', name: 'The Wall', description: 'Uma enorme muralha de gelo que protege o reino dos perigos além. Com mais de 200 metros de altura, a Muralha é uma estrutura monumental e guarnecida pela Patrulha da Noite. Este bastião enfrenta as ameaças das terras geladas ao norte, e é um símbolo de vigilância e sacrifício.' },
  { kingdom_name: 'The North', name: 'White Harbor', description: 'O maior porto do Norte, uma cidade movimentada conhecida pelo seu comércio e força naval. White Harbor é crucial para o comércio do Norte e serve como um elo vital entre o Norte e o resto de Westeros, destacando-se como um centro econômico e cultural.' },

  { kingdom_name: 'The Reach', name: 'Highgarden', description: 'A sede da Casa Tyrell, renomada por seus belos jardins e terras férteis. Highgarden é um paraíso de vegetação exuberante e vinhedos, com uma arquitetura magnífica que reflete a riqueza e a influência da Casa Tyrell. É um símbolo de prosperidade e cultura refinada.' },
  { kingdom_name: 'The Reach', name: 'Oldtown', description: 'Uma das cidades mais antigas de Westeros, conhecida por seus maestres e a Cidadela. Oldtown é um centro de aprendizado e conhecimento, e sua Cidadela é onde os maestres são treinados. A cidade é famosa por suas bibliotecas, instituições acadêmicas e por sua rica história.' },
  { kingdom_name: 'The Reach', name: 'Brightwater Keep', description: 'Um castelo formidável com uma grande e rica propriedade, ocupando uma posição estratégica no Reach. Brightwater Keep é conhecido por sua força defensiva e por sua localização estratégica ao longo das rotas comerciais do Reach. É um bastião de poder e segurança.' },

  { kingdom_name: 'The Vale', name: 'The Eyrie', description: 'Uma fortaleza elevada nas montanhas, considerada quase impenetrável. A Eyrie é uma fortaleza lendária que domina as montanhas do Vale, e sua posição elevada a torna uma das fortalezas mais seguras de Westeros. É um símbolo de poder e segurança impenetrável.' },
  { kingdom_name: 'The Vale', name: 'Runestone', description: 'Uma fortaleza ancestral da Casa Royce, conhecida por suas defesas sólidas e localização estratégica. Runestone é uma fortaleza robusta e antiga, famosa por suas muralhas impenetráveis e pela lealdade de seus habitantes à Casa Royce. É um pilar de resistência e lealdade no Vale.' },

  { kingdom_name: 'The Stormlands', name: 'Storm’s End', description: 'A sede da Casa Baratheon, localizada na costa e conhecida por sua resistência durante as tempestades. Storm’s End é uma fortaleza poderosa que resiste às tempestades do litoral e é a base de poder da Casa Baratheon. É uma fortaleza icônica, representando força e resistência.' },
  { kingdom_name: 'The Stormlands', name: 'Grimstone', description: 'Uma fortaleza robusta na região montanhosa, conhecida por sua fortificação e história de batalhas. Grimstone é uma fortaleza temida e respeitada, conhecida por suas defesas e pela bravura de seus habitantes. É um símbolo de resiliência e poder militar.' },

  { kingdom_name: 'Dorne', name: 'Sunspear', description: 'A sede da Casa Martell, localizada no sul quente e árido, conhecida por sua arquitetura distinta e liderança feroz. Sunspear é uma cidade fortificada que serve como centro de governo e como símbolo da independência de Dorne. É um bastião de resistência e estratégia.' },
  { kingdom_name: 'Dorne', name: 'Planky Town', description: 'Uma importante cidade portuária em Dorne, conhecida por seu comércio e ambiente vibrante. Planky Town é um ponto de comércio crucial e um centro cultural para o sul de Westeros. É um centro de atividade econômica e cultural vibrante.' },

  { kingdom_name: 'The Riverlands', name: 'Riverrun', description: 'A sede da Casa Tully, localizada às margens do rio, conhecida por sua influência e importância na região. Riverrun é uma fortaleza fortificada com uma rica história e importância estratégica para a Casa Tully. É um bastião de influência e gestão estratégica.' },
  { kingdom_name: 'The Riverlands', name: 'The Twins', description: 'Uma fortaleza de ponte estratégica, controlada pelos Freys, importante para as travessias nos rios da região. The Twins é uma fortaleza que controla uma importante rota comercial e é conhecida por suas defesas e sua importância política. É um ponto crucial para a movimentação de tropas e mercadorias.' },
  { kingdom_name: 'The Riverlands', name: 'Harrenhal', description: 'Uma colossal e desolada fortaleza, famosa por sua grandiosidade e pela tragédia que a marcou. Harrenhal é uma das maiores estruturas de Westeros, mas sua história é marcada por calamidades e abandono. É um símbolo de decadência e mistério.' },

  { kingdom_name: 'The Iron Islands', name: 'Pyke', description: 'A sede da Casa Greyjoy, localizada na ilha principal das Ilhas de Ferro, conhecida por seus navegantes e cultura guerreira. Pyke é uma fortaleza à beira-mar, conhecida por sua arquitetura peculiar e por sua marinha temida. É um bastião de poder naval e cultura guerreira.' },
  { kingdom_name: 'The Iron Islands', name: 'Harlaw', description: 'Uma das ilhas maiores, conhecida por sua fortaleza robusta e influência naval. Harlaw é um importante centro para a Casa Harlaw e um ponto estratégico para a defesa das Ilhas de Ferro. É um bastião de força naval e segurança estratégica.' },

  { kingdom_name: 'Westerlands', name: 'Casterly Rock', description: 'A sede ancestral da Casa Lannister, localizada em uma impressionante formação rochosa sobre o mar. Casterly Rock é um símbolo de poder e riqueza, com uma fortaleza robusta e uma vista panorâmica deslumbrante. É a base do poder da Casa Lannister e um centro de influência e riqueza.' },
  { kingdom_name: 'Westerlands', name: 'Lannisport', description: 'Uma cidade portuária importante, conhecida por seu comércio e riqueza. Lannisport é um dos centros econômicos mais vibrantes de Westeros, facilitando o comércio e servindo como um porto crucial para as riquezas do reino. É um centro de atividade comercial e prosperidade econômica.' }
  
]

PERSON = [
  { kingdom_name: 'The North', name: 'Eddard Stark', description: 'O honrado Lorde de Winterfell, conhecido por sua justiça e lealdade à sua família e aos seus deveres. Eddard Stark é um líder respeitado e um bastião de moralidade e ordem no Norte. Seu compromisso com a justiça e sua dedicação à proteção de seu reino fazem dele uma figura central na luta contra as ameaças que se aproximam.' },
  { kingdom_name: 'The North', name: 'Jon Snow', description: 'Um jovem bastardo criado em Winterfell, conhecido por sua bravura e senso de justiça. Jon Snow é um guerreiro habilidoso e um líder natural, com um forte sentido de honra e dever. Sua jornada de um bastardo para um líder importante é marcada por desafios e sacrifícios, e ele desempenha um papel crucial na defesa do Norte.' },
  { kingdom_name: 'The North', name: 'Bran Stark', description: 'O filho mais novo de Eddard Stark, conhecido por suas habilidades psíquicas e sua conexão com o mundo místico. Bran Stark é um personagem enigmático com habilidades que vão além da compreensão comum, desempenhando um papel vital na compreensão e enfrentamento das forças sobrenaturais que ameaçam o reino.' },
  { kingdom_name: 'The North', name: 'Arya Stark', description: 'A filha mais nova de Eddard Stark, conhecida por sua destreza com a espada e seu desejo de aventura. Arya Stark é uma guerreira feroz e independente, com habilidades de combate e uma determinação implacável. Sua jornada é marcada pela busca de justiça e pela luta contra as adversidades.' },
  { kingdom_name: 'The North', name: 'Sansa Stark', description: 'A filha mais velha de Eddard Stark, conhecida por sua inteligência e habilidade política. Sansa Stark é uma estrategista habilidosa e uma figura central na política do Norte. Sua jornada é marcada por seu crescimento pessoal e sua capacidade de navegar nas complexidades do poder e da diplomacia.' },
  { kingdom_name: 'The North', name: 'Rickon Stark', description: 'O filho mais novo de Eddard Stark, conhecido por sua vivacidade e energia. Rickon Stark é um jovem impetuoso e cheio de vida, que representa a esperança e o futuro da Casa Stark. Sua presença é um lembrete da continuidade e da força da família Stark.' },

  { kingdom_name: 'The Reach', name: 'Margaery Tyrell', description: 'A esposa do rei e uma figura carismática e astuta conhecida por sua influência política e habilidade diplomática. Margaery Tyrell é uma estrategista habilidosa e uma líder carismática, que desempenha um papel central nas intrigas políticas do Reach e além. Sua inteligência e charme a tornam uma figura influente e respeitada.' },
  { kingdom_name: 'The Reach', name: 'Olenna Tyrell', description: 'A matriarca da Casa Tyrell, conhecida por sua sagacidade e astúcia. Olenna Tyrell é uma estrategista experiente e uma figura formidável no campo político. Sua capacidade de manipular e influenciar os eventos a torna uma das figuras mais poderosas e temidas em Westeros.' },
  { kingdom_name: 'The Reach', name: 'Loras Tyrell', description: 'Um cavaleiro renomado da Casa Tyrell, conhecido por sua bravura e habilidade em combate. Loras Tyrell é um guerreiro habilidoso e um líder militar respeitado, cuja lealdade e coragem são amplamente reconhecidas. Ele desempenha um papel crucial na proteção e na expansão dos interesses da Casa Tyrell.' },
  { kingdom_name: 'The Reach', name: 'Garlan Tyrell', description: 'O irmão de Margaery e Loras Tyrell, conhecido por sua habilidade militar e liderança. Garlan Tyrell é um comandante competente e um líder natural, cuja experiência e dedicação à sua casa o tornam uma figura respeitada e influente no Reach.' },

  { kingdom_name: 'The Vale', name: 'Lysa Arryn', description: 'A senhora do Vale, conhecida por sua paixão e intensidade. Lysa Arryn é uma figura complexa, marcada por sua lealdade e suas emoções fortes. Sua liderança é marcada por um desejo de proteger seu reino e sua família, apesar dos desafios e das intrigas políticas que enfrenta.' },
  { kingdom_name: 'The Vale', name: 'Robin Arryn', description: 'O jovem herdeiro do Vale, conhecido por sua vulnerabilidade e necessidade de proteção. Robin Arryn é uma figura central na política do Vale, e sua juventude e fragilidade o tornam um alvo de intrigas e manipulações. Seu papel no reino é fundamental para a estabilidade e o futuro da Casa Arryn.' },
  { kingdom_name: 'The Vale', name: 'Petyr Baelish', description: 'Um político astuto e manipulador, conhecido por suas habilidades em intriga e poder. Petyr Baelish é um mestre da política e da manipulação, cuja ambição e inteligência o tornam uma figura central nas disputas de poder no Vale e além.' },

  { kingdom_name: 'The Stormlands', name: 'Robert Baratheon', description: 'O rei das Terras das Tempestades e líder de uma das casas mais poderosas de Westeros. Robert Baratheon é um guerreiro robusto e um líder carismático, conhecido por sua bravura e pela força de sua casa. Seu governo é marcado por suas conquistas militares e seu desejo de proteger seu reino.' },
  { kingdom_name: 'The Stormlands', name: 'Stannis Baratheon', description: 'O irmão de Robert, conhecido por sua dedicação e rigor. Stannis Baratheon é um líder militar e estratégico, cuja lealdade e compromisso com a justiça o tornam uma figura respeitada e temida. Seu papel nas campanhas militares e na defesa das Terras das Tempestades é crucial.' },
  { kingdom_name: 'The Stormlands', name: 'Renly Baratheon', description: 'O irmão mais jovem de Robert e Stannis, conhecido por seu charme e habilidades de liderança. Renly Baratheon é um líder carismático e um guerreiro habilidoso, cuja popularidade e influência desempenham um papel importante nas disputas políticas das Terras das Tempestades.' },

  { kingdom_name: 'Dorne', name: 'Oberyn Martell', description: 'O Príncipe de Dorne, conhecido por sua habilidade em combate e charme irresistível. Oberyn Martell é um guerreiro e diplomata, cuja habilidade com a lança e seu carisma o tornam uma figura temida e respeitada. Sua influência e habilidades de combate são amplamente reconhecidas.' },
  { kingdom_name: 'Dorne', name: 'Arianne Martell', description: 'A filha do Príncipe Oberyn, conhecida por sua inteligência e ambição. Arianne Martell é uma estrategista astuta e uma figura central nas intrigas políticas de Dorne. Sua capacidade de manipular e influenciar eventos a torna uma figura poderosa e respeitada.' },
  { kingdom_name: 'Dorne', name: 'Doran Martell', description: 'O Príncipe governante de Dorne, conhecido por sua sabedoria e paciência. Doran Martell é um líder sagaz e estratégico, cuja habilidade em governar e manter a paz em Dorne é amplamente reconhecida. Seu papel é crucial na manutenção da estabilidade e na condução das políticas de Dorne.' },

  { kingdom_name: 'The Riverlands', name: 'Edmure Tully', description: 'O Senhor de Riverrun, conhecido por sua lealdade e habilidade militar. Edmure Tully é um comandante respeitado e um líder devotado, cuja dedicação à sua casa e ao reino é amplamente reconhecida. Seu papel nas campanhas militares e na defesa dos Rios é crucial.' },
  { kingdom_name: 'The Riverlands', name: 'Catelyn Stark', description: 'A esposa de Eddard Stark e mãe dedicada, conhecida por sua força e determinação. Catelyn Stark é uma figura central na administração dos Rios e na defesa de sua família. Sua lealdade e habilidades de liderança a tornam uma figura respeitada e influente.' },
  { kingdom_name: 'The Riverlands', name: 'Brynden Rivers', description: 'Um membro misterioso da família Tully, conhecido por suas habilidades mágicas e seu papel nas lendas da região. Brynden Rivers é uma figura enigmática, cuja presença e habilidades são marcadas por mistério e poder. Sua influência nas histórias e lendas dos Rios é significativa.' },

  { kingdom_name: 'The Iron Islands', name: 'Balon Greyjoy', description: 'O Senhor das Ilhas de Ferro, conhecido por seu governo severo e sua habilidade em combate naval. Balon Greyjoy é um líder temido e respeitado, cuja influência nas Ilhas de Ferro e na marinha é amplamente reconhecida. Seu papel é crucial na defesa e expansão das Ilhas de Ferro.' },
  { kingdom_name: 'The Iron Islands', name: 'Yara Greyjoy', description: 'A filha de Balon, conhecida por sua habilidade naval e espírito indomável. Yara Greyjoy é uma comandante habilidosa e uma figura respeitada nas Ilhas de Ferro, cuja coragem e habilidades de liderança são amplamente reconhecidas.' },
  { kingdom_name: 'The Iron Islands', name: 'Victarion Greyjoy', description: 'O irmão de Balon e um dos líderes militares mais temidos, conhecido por sua bravura e habilidades de combate. Victarion Greyjoy é um guerreiro experiente e um comandante formidável, cuja força e habilidade são cruciais para a defesa das Ilhas de Ferro.' },

  { kingdom_name: 'Westerlands', name: 'Tywin Lannister', description: 'O chefe da Casa Lannister e uma das figuras mais poderosas de Westeros. Tywin Lannister é conhecido por sua habilidade política e militar, e por sua gestão rigorosa de sua casa. Ele é um estrategista astuto e uma figura dominante no cenário político de Westeros.' },
  { kingdom_name: 'Westerlands', name: 'Cersei Lannister', description: 'A filha de Tywin Lannister e uma das personagens mais influentes da política de Westeros. Cersei é conhecida por sua ambição, inteligência e sua capacidade de manipular a política para seu próprio benefício. Ela tem um papel central nas intrigas e nas lutas pelo poder em Westeros.' },
  { kingdom_name: 'Westerlands', name: 'Jaime Lannister', description: 'O filho mais velho de Tywin Lannister, conhecido como o "Mão do Rei" e um dos maiores espadachins de Westeros. Jaime Lannister é famoso por suas habilidades em combate e por sua lealdade à sua família, apesar de suas ações controversas e conflitos internos.' },
  { kingdom_name: 'Westerlands', name: 'Tyrion Lannister', description: 'O menor dos filhos de Tywin Lannister, conhecido por sua inteligência afiada e habilidades políticas. Tyrion Lannister é um personagem astuto e perspicaz, que usa sua mente brilhante para navegar pelas complexidades da política e para lutar contra as adversidades que enfrenta por ser um anão.' }

]
